#!/usr/bin/env bash


dotfiles=$HOME/.dotfiles


function install_brew() {
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
}

function install_zsh() {
	ln -s $dotfiles/zsh/zshrc $HOME/.zshrc
	mkdir -p $HOME/.cache/zsh
}

function install_tmux() {
	brew install tmux fzf fd
	ln -s $dotfiles/tmux/tmux.conf $HOME/.tmux.conf
	sudo ln -s $dotfiles/tmux/tmux-cd /usr/local/bin/tmux-cd
	sudo ln -s $dotfiles/tmux/tmux-goto /usr/local/bin/tmux-goto
}

function install_git() {
	email="$(grep -oE '[^[:space:]]+$' ~/.ssh/id_ed25519.pub)"

	brew install git
	ln -s $dotfiles/git/gitconfig $HOME/.gitconfig
	echo "$email $(cat ~/.ssh/id_ed25519.pub)" > $dotfiles/git/allowed_signers
	git config --global user.email "$email"
	git config --global user.signingKey "$(cat ~/.ssh/id_ed25519.pub)"
	git config --global gpg.ssh.allowedSignersFile $dotfiles/git/allowed_signers
}

function install_nvim() {
	brew install neovim
	ln -s $dotfiles/nvim $HOME/.config/nvim
	git clone --depth 1 https://github.com/wbthomason/packer.nvim $HOME/.local/share/nvim/site/pack/packer/start/packer.nvim
}

function install_go() {
	brew install go
	mkdir -p $HOME/dev/.go
}

function install_zig() {
	brew install zig

	mkdir -p $dotfiles/zig/zls $dotfiles/zig/bin
	curl -L https://github.com/zigtools/zls/releases/download/0.9.0/x86_64-macos.tar.xz | tar -xJ --strip-components=1 -C $dotfiles/zig/zls
	chmod +x $dotfiles/zig/zls/zls
	mv $dotfiles/zig/zls/zls $dotfiles/zig/bin/zls
	sudo ln -s $dotfiles/zig/bin/zls /usr/local/bin/zls
}



if [[ -z $@ ]]; then
	tools="brew zsh tmux git nvim go zig"
else
	tools="$@"
fi

for tool in $tools; do
	case $tool in
		brew) install_brew;;
		zsh)  install_zsh;;
		tmux) install_tmux;;
		git)  install_git;;
		nvim) install_nvim;;
		go)  install_go;;
		zig)  install_zig;;
		*)    echo "error: unknown parameter $tool" >> /dev/stderr; exit 1;;
	esac
done
