#!/usr/bin/env bash


if [[ -z $EMAIL ]]; then
	echo "error: variable EMAIL not defined" >> /dev/stderr
	exit 1
fi

ssh-keygen -o -a 64 -t ed25519 -f ~/.ssh/id_ed25519 -C "$EMAIL"
echo "Host *\n  AddKeysToAgent yes\n  UseKeychain yes\n  IdentityFile ~/.ssh/id_ed25519" > $HOME/.ssh/config
ssh-add --apple-use-keychain ~/.ssh/id_ed25519

cat ~/.ssh/id_ed25519.pub
